### ISSUE TITLE
configure missing

### ISSUE THREAD

**Issue by edytzul** [independentcod/PerlIRCSSL_VNCbypass#1]
HI!  configure missing..

edy@Brasov:~/PerlIRCSSL_VNCbypass$ ls
ccfinder  Config  perlircssl.pl  rc-local.service  README.md  sshd_banner  sshd_config
edy@Brasov:~/PerlIRCSSL_VNCbypass$ ./configure
-bash: ./configure: No such file or directory

**Comment by ind3p3nd3nt** [comment]
Use: ./Config
